DROP DATABASE IF EXISTS Miau;

CREATE DATABASE Miau;
USE Miau;

CREATE TABLE Usuario (
ID INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL, 
Apellido VARCHAR(50) NOT NULL,
Correo VARCHAR(50) NOT NULL, 
Celular INT(11) NOT NULL,
Cedula INT NOT NULL,
Contraseña VARCHAR(50)
);

CREATE TABLE Gatos (
ID INT AUTO_INCREMENT PRIMARY KEY,
Raza VARCHAR(50) NOT NULL, 
Nombre VARCHAR(50) NOT NULL, 
Historial VARCHAR(50) NOT NULL, 
Años INT NOT NULL
);

CREATE TABLE Cita (
ID INT AUTO_INCREMENT PRIMARY KEY, 
Fecha DATETIME NOT NULL, 
ID_Usuario INT NOT NULL, 
ID_Gato INT NOT NULL, 
FOREIGN KEY (ID_Gato) REFERENCES Gatos(ID),
FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID)
);

CREATE TABLE Adopción(
ID INT AUTO_INCREMENT PRIMARY KEY, 
Descripcion_seguimiento VARCHAR(200) NOT NULL, 
Descripcion_perfil_felino VARCHAR(200) NOT NULL,
fecha_adopcion DATETIME NOT NULL,
ID_cita INT NOT NULL,
ID_Usuario INT NOT NULL, 
ID_Gato INT NOT NULL,
FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID),
FOREIGN KEY (ID_Gato) REFERENCES Gatos(ID)
);
